# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/sync_ram_18bit/sync_ram_18bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_ram_18bit || ORIG_REF_NAME==sync_ram_18bit} -quiet] -quiet

# IP: ip/jesd204_tx_phy/jesd204_tx_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_tx_phy || ORIG_REF_NAME==jesd204_tx_phy} -quiet] -quiet

# IP: ip/jesd204_tx_phy/ip_0/jesd204_tx_phy_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_tx_phy_gt || ORIG_REF_NAME==jesd204_tx_phy_gt} -quiet] -quiet

# IP: ip/ila_adc_256/ila_adc_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_adc_256 || ORIG_REF_NAME==ila_adc_256} -quiet] -quiet

# IP: ip/adc_fifo/adc_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc_fifo || ORIG_REF_NAME==adc_fifo} -quiet] -quiet

# IP: ip/jesd204_0_phy/jesd204_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==jesd204_0_phy || ORIG_REF_NAME==jesd204_0_phy} -quiet] -quiet

# Block Designs: bd/ADC/ADC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC || ORIG_REF_NAME==ADC} -quiet] -quiet

# IP: bd/ADC/ip/ADC_sysref_gen_0_0/ADC_sysref_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_sysref_gen_0_0 || ORIG_REF_NAME==ADC_sysref_gen_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_axi_lite_spi_0_0/ADC_axi_lite_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_axi_lite_spi_0_0 || ORIG_REF_NAME==ADC_axi_lite_spi_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_SPI_choose_0_0/ADC_SPI_choose_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_SPI_choose_0_0 || ORIG_REF_NAME==ADC_SPI_choose_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_ctrl_204b_0_0/ADC_ctrl_204b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_ctrl_204b_0_0 || ORIG_REF_NAME==ADC_ctrl_204b_0_0} -quiet] -quiet

# IP: ip/sync_ram_18bit/sync_ram_18bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_ram_18bit || ORIG_REF_NAME==sync_ram_18bit} -quiet] -quiet

# IP: bd/ADC/ip/ADC_ADC_spi_interface_0_0_0_0/ADC_ADC_spi_interface_0_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_ADC_spi_interface_0_0_0_0 || ORIG_REF_NAME==ADC_ADC_spi_interface_0_0_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_vio_0_0/ADC_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_vio_0_0 || ORIG_REF_NAME==ADC_vio_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_axi_quad_spi_0_0/ADC_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_axi_quad_spi_0_0 || ORIG_REF_NAME==ADC_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_axi_gpio_0_0 || ORIG_REF_NAME==ADC_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_sync_0/ADC_lmk04828_sync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_sync_0 || ORIG_REF_NAME==ADC_lmk04828_sync_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_sync_1/ADC_lmk04828_sync_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_sync_1 || ORIG_REF_NAME==ADC_lmk04828_sync_1} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_sync_2/ADC_lmk04828_sync_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_sync_2 || ORIG_REF_NAME==ADC_lmk04828_sync_2} -quiet] -quiet

# IP: bd/ADC/ip/ADC_config_done_0/ADC_config_done_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_config_done_0 || ORIG_REF_NAME==ADC_config_done_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_ld_0/ADC_lmk04828_ld_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_ld_0 || ORIG_REF_NAME==ADC_lmk04828_ld_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_spi_0/ADC_lmk04828_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_spi_0 || ORIG_REF_NAME==ADC_lmk04828_spi_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_microblaze_0_0/ADC_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_microblaze_0_0 || ORIG_REF_NAME==ADC_microblaze_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_mdm_1_0/ADC_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_mdm_1_0 || ORIG_REF_NAME==ADC_mdm_1_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_rst_adc_clk_100M_0/ADC_rst_adc_clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_rst_adc_clk_100M_0 || ORIG_REF_NAME==ADC_rst_adc_clk_100M_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_xbar_0/ADC_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_xbar_0 || ORIG_REF_NAME==ADC_xbar_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_microblaze_0_axi_periph_0/ADC_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ADC_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_dlmb_v10_0/ADC_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_dlmb_v10_0 || ORIG_REF_NAME==ADC_dlmb_v10_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_ilmb_v10_0/ADC_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_ilmb_v10_0 || ORIG_REF_NAME==ADC_ilmb_v10_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_dlmb_bram_if_cntlr_0/ADC_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ADC_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_ilmb_bram_if_cntlr_0/ADC_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ADC_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmb_bram_0/ADC_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmb_bram_0 || ORIG_REF_NAME==ADC_lmb_bram_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_adc_lmx2592_0/ADC_adc_lmx2592_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_adc_lmx2592_0 || ORIG_REF_NAME==ADC_adc_lmx2592_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_dac_lmx2592_0/ADC_dac_lmx2592_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_dac_lmx2592_0 || ORIG_REF_NAME==ADC_dac_lmx2592_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_sync_3/ADC_lmk04828_sync_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_sync_3 || ORIG_REF_NAME==ADC_lmk04828_sync_3} -quiet] -quiet

# IP: bd/ADC/ip/ADC_ada16d6000_1_rst_0/ADC_ada16d6000_1_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_ada16d6000_1_rst_0 || ORIG_REF_NAME==ADC_ada16d6000_1_rst_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_jesd_rst_p_0/ADC_jesd_rst_p_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_jesd_rst_p_0 || ORIG_REF_NAME==ADC_jesd_rst_p_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_jesd_sysref_rst_0/ADC_jesd_sysref_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_jesd_sysref_rst_0 || ORIG_REF_NAME==ADC_jesd_sysref_rst_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_sysref_div_0 || ORIG_REF_NAME==ADC_sysref_div_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_lmk04828_ld_1/ADC_lmk04828_ld_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_lmk04828_ld_1 || ORIG_REF_NAME==ADC_lmk04828_ld_1} -quiet] -quiet

# IP: bd/ADC/ip/ADC_axi_lite_spi_0_1/ADC_axi_lite_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_axi_lite_spi_0_1 || ORIG_REF_NAME==ADC_axi_lite_spi_0_1} -quiet] -quiet

# IP: bd/ADC/ip/ADC_adc1_spi_0/ADC_adc1_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_adc1_spi_0 || ORIG_REF_NAME==ADC_adc1_spi_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_adc1_spi_1/ADC_adc1_spi_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_adc1_spi_1 || ORIG_REF_NAME==ADC_adc1_spi_1} -quiet] -quiet

# IP: bd/ADC/ip/ADC_tier2_xbar_0_0/ADC_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_tier2_xbar_0_0 || ORIG_REF_NAME==ADC_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_tier2_xbar_1_0/ADC_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_tier2_xbar_1_0 || ORIG_REF_NAME==ADC_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/ADC/ip/ADC_tier2_xbar_2_0/ADC_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_tier2_xbar_2_0 || ORIG_REF_NAME==ADC_tier2_xbar_2_0} -quiet] -quiet

# XDC: ip/sync_ram_18bit/sync_ram_18bit_ooc.xdc

# XDC: ip/jesd204_tx_phy/synth/jesd204_tx_phy_ooc.xdc

# XDC: ip/jesd204_tx_phy/synth/jesd204_tx_phy.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_tx_phy || ORIG_REF_NAME==jesd204_tx_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/jesd204_tx_phy/synth/jesd204_tx_phy_clock_group.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_tx_phy || ORIG_REF_NAME==jesd204_tx_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/jesd204_tx_phy/synth/jesd204_tx_phy_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_tx_phy || ORIG_REF_NAME==jesd204_tx_phy} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/jesd204_tx_phy/ip_0/jesd204_tx_phy_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==jesd204_tx_phy_gt || ORIG_REF_NAME==jesd204_tx_phy_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/jesd204_tx_phy/ip_0/jesd204_tx_phy_gt_ooc.xdc

# XDC: ip/sync_ram_18bit/sync_ram_18bit_ooc.xdc

# XDC: bd/ADC/ADC_ooc.xdc
