# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1927-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/hdl/ADC_wrapper.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/TOP_DAC.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/adc_analysis.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/yth/yth_AAD12D2000_2G_18.3_v1.0/project_1/project_1.srcs/sources_1/new/adc_module.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/yth/yth_AAD12D2000_2G_18.3_v1.0/project_1/project_1.srcs/sources_1/new/adc_top.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/ad9208_2ch_top/axi_cfg.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/axi_lite_write.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/ad9208_2ch_top/axi_proc.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/ad9208_2ch_top/axi_top.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/clock_module.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/da_spi_module.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/dac_top.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/yth/jesd204_0_ex/imports/jesd204_0_clocking.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/imports/imports/yth/jesd204_0_ex/imports/jesd204_0_support.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/jesd204_1_support.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/jesd204_tx_clocking.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/sine_gen.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/sysref_gen_dac.v}
  {D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/new/top.v}
}
read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/jesd204_tx_phy.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/synth/jesd204_tx_phy_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/synth/jesd204_tx_phy.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/synth/jesd204_tx_phy_clock_group.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/synth/jesd204_tx_phy_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/ip_0/jesd204_tx_phy_gt.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx_phy/ip_0/jesd204_tx_phy_gt_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/ila_adc_256/ila_adc_256.xci}}
set_property used_in_synthesis false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/ila_adc_256/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/ila_adc_256/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/ila_adc_256/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/ila_adc_256/ila_adc_256_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/adc_fifo/adc_fifo.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/adc_fifo/adc_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/adc_fifo/adc_fifo_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/adc_fifo/adc_fifo_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/jesd204_0_phy.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/synth/jesd204_0_phy_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/synth/jesd204_0_phy.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/synth/jesd204_0_phy_clock_group.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/synth/jesd204_0_phy_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/ip_0/jesd204_0_phy_gt.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/ip_0/jesd204_0_phy_gt_ooc.xdc}}]

add_files {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ADC.bd}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ctrl_204b_0_0/ADC_ctrl_204b_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_vio_0_0/ADC_vio_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_vio_0_0/ADC_vio_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_quad_spi_0_0/ADC_axi_quad_spi_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_quad_spi_0_0/ADC_axi_quad_spi_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_quad_spi_0_0/ADC_axi_quad_spi_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_quad_spi_0_0/ADC_axi_quad_spi_0_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_axi_gpio_0_0/ADC_axi_gpio_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_0/ADC_lmk04828_sync_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_0/ADC_lmk04828_sync_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_0/ADC_lmk04828_sync_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_1/ADC_lmk04828_sync_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_1/ADC_lmk04828_sync_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_1/ADC_lmk04828_sync_1.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_2/ADC_lmk04828_sync_2_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_2/ADC_lmk04828_sync_2_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_2/ADC_lmk04828_sync_2.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_config_done_0/ADC_config_done_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_config_done_0/ADC_config_done_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_config_done_0/ADC_config_done_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_ld_0/ADC_lmk04828_ld_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_ld_0/ADC_lmk04828_ld_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_ld_0/ADC_lmk04828_ld_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_spi_0/ADC_lmk04828_spi_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_spi_0/ADC_lmk04828_spi_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_spi_0/ADC_lmk04828_spi_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_spi_0/ADC_lmk04828_spi_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_microblaze_0_0/ADC_microblaze_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_microblaze_0_0/ADC_microblaze_0_0_ooc_debug.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_microblaze_0_0/ADC_microblaze_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_mdm_1_0/ADC_mdm_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_mdm_1_0/ADC_mdm_1_0_ooc_trace.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_rst_adc_clk_100M_0/ADC_rst_adc_clk_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_rst_adc_clk_100M_0/ADC_rst_adc_clk_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_rst_adc_clk_100M_0/ADC_rst_adc_clk_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_xbar_0/ADC_xbar_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dlmb_v10_0/ADC_dlmb_v10_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dlmb_v10_0/ADC_dlmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ilmb_v10_0/ADC_ilmb_v10_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ilmb_v10_0/ADC_ilmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dlmb_bram_if_cntlr_0/ADC_dlmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ilmb_bram_if_cntlr_0/ADC_ilmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmb_bram_0/ADC_lmb_bram_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_adc_lmx2592_0/ADC_adc_lmx2592_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_adc_lmx2592_0/ADC_adc_lmx2592_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_adc_lmx2592_0/ADC_adc_lmx2592_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_adc_lmx2592_0/ADC_adc_lmx2592_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dac_lmx2592_0/ADC_dac_lmx2592_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dac_lmx2592_0/ADC_dac_lmx2592_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dac_lmx2592_0/ADC_dac_lmx2592_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_dac_lmx2592_0/ADC_dac_lmx2592_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_3/ADC_lmk04828_sync_3_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_3/ADC_lmk04828_sync_3_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_sync_3/ADC_lmk04828_sync_3.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ada16d6000_1_rst_0/ADC_ada16d6000_1_rst_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ada16d6000_1_rst_0/ADC_ada16d6000_1_rst_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ada16d6000_1_rst_0/ADC_ada16d6000_1_rst_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_jesd_rst_p_0/ADC_jesd_rst_p_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_jesd_rst_p_0/ADC_jesd_rst_p_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_jesd_rst_p_0/ADC_jesd_rst_p_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_jesd_sysref_rst_0/ADC_jesd_sysref_rst_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_jesd_sysref_rst_0/ADC_jesd_sysref_rst_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_jesd_sysref_rst_0/ADC_jesd_sysref_rst_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_ld_1/ADC_lmk04828_ld_1_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_ld_1/ADC_lmk04828_ld_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_lmk04828_ld_1/ADC_lmk04828_ld_1.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_tier2_xbar_0_0/ADC_tier2_xbar_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_tier2_xbar_1_0/ADC_tier2_xbar_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_tier2_xbar_2_0/ADC_tier2_xbar_2_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/bd/ADC/ADC_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/vio_0/vio_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/vio_0/vio_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/vio_1/vio_1.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/vio_1/vio_1.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/vio_1/vio_1_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0/jesd204_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_ooc.xdc}}]

read_ip -quiet {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx/jesd204_tx.xci}}
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx/synth/jesd204_tx.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/sources_1/ip/jesd204_tx/synth/jesd204_tx_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/constrs_1/new/top.xdc}}
set_property used_in_implementation false [get_files {{D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/chengdu_BIT/11_cs_nwe _channel4/project_1/project_1.srcs/constrs_1/new/top.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7vx690tffg1927-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
