# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_tx/jesd204_tx.xci
# IP: The module: 'jesd204_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_tx/synth/jesd204_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_tx'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_tx/synth/jesd204_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_tx/jesd204_tx.xci
# IP: The module: 'jesd204_tx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_tx/synth/jesd204_tx.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_tx/synth/jesd204_tx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_tx'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
