# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0.xci
# IP: The module: 'ADC_sysref_div_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_sysref_div_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_sysref_div_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_sysref_div_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0.xci
# IP: The module: 'ADC_sysref_div_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_sysref_div_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_sysref_div_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_sysref_div_0/ADC_sysref_div_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_sysref_div_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
