# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_adc.xci
# IP: The module: 'ila_adc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_adc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_adc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_adc.xci
# IP: The module: 'ila_adc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/work_panyanjiao/2306_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_yzb3/project_1/project_1.srcs/sources_1/ip/ila_adc/ila_adc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_adc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
