# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ctrl_204b_0_0/ADC_ctrl_204b_0_0.xci
# IP: The module: 'ADC_ctrl_204b_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/ip/sync_ram_18bit/sync_ram_18bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_ram_18bit || ORIG_REF_NAME==sync_ram_18bit} -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/ip/sync_ram_18bit/sync_ram_18bit_ooc.xdc

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ctrl_204b_0_0/ADC_ctrl_204b_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_ctrl_204b_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ctrl_204b_0_0/ADC_ctrl_204b_0_0.xci
# IP: The module: 'ADC_ctrl_204b_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/ip/sync_ram_18bit/sync_ram_18bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sync_ram_18bit || ORIG_REF_NAME==sync_ram_18bit} -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/ip/sync_ram_18bit/sync_ram_18bit_ooc.xdc

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD_0825_1/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_ctrl_204b_0_0/ADC_ctrl_204b_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_ctrl_204b_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
