# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk.xci
# IP: The module: 'gt_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk.xci
# IP: The module: 'gt_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_ADDA_0829_debug/project_1/project_1.srcs/sources_1/ip/gt_clk/gt_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gt_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
