set_property SRC_FILE_INFO {cfile:d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc rfile:../../../project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 2  -from [get_cells -hier -filter {name =~ *i_axi_lite_ipif/I_SLAVE_ATTACHMENT/bus2ip_addr_reg_reg* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 2  -from [get_cells -hier -filter {name =~ *i_axi_lite_ipif/I_SLAVE_ATTACHMENT/GEN_USE_WSTRB.bus2ip_be_reg_reg* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold 2  -from [get_cells -hier -filter {name =~ *i_axi_lite_ipif/I_SLAVE_ATTACHMENT/I_DECODER/GEN_BKEND_CE_REGISTERS[0].rdce_out_i_reg[0] && IS_SEQUENTIAL}] -to [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-1 -description {Safe RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*/jesd204_i/inst/IP2Bus_Data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-1 -description {Safe RW control registers} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*/jesd204_block_i/IP2Bus_Data_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-1 -description {False paths from config registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_cfg_*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-1 -description {False paths from config registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_sysref_delay_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-2 -description {False paths from config registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_cfg_*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-4 -description {Multibit crossing from lid registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*tx_cfg_lid*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-10 -description {Safe simple synchroniser for sysref captured} -from [get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*got_sysref_r_reg*}] ] -to   [get_pins -filter {REF_PIN_NAME=~D} -of [get_cells -hier -filter {name=~*sysref_captured/syncstages_ff_reg[0]*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-10 -description {False paths from config registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_cfg_*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-11 -description {False paths from config registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_cfg_*_reg*}] ]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user JESD204 -type CDC -id CDC-13 -description {False paths from config registers are safe} -from [ get_pins -filter {REF_PIN_NAME=~C} -of [get_cells -hier -filter {name=~*x_cfg_*_reg*}] ]
