-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Wed Aug 24 18:30:25 2022
-- Host        : SKY-20191122TPZ running 64-bit Service Pack 1  (build 7601)
-- Command     : write_vhdl -force -mode synth_stub
--               E:/work_panyanjiao/37_YTH2/new_2/pro/ad/project_vivado18.3_YTH2_AD/project_1/project_1.srcs/sources_1/ip/jesd204_0_phy/jesd204_0_phy_stub.vhdl
-- Design      : jesd204_0_phy
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7vx690tffg1927-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity jesd204_0_phy is
  Port ( 
    gt0_txresetdone_out : out STD_LOGIC;
    gt0_rxresetdone_out : out STD_LOGIC;
    gt0_cplllock_out : out STD_LOGIC;
    gt0_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt0_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt0_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt0_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt0_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_txpolarity_in : in STD_LOGIC;
    gt0_txinhibit_in : in STD_LOGIC;
    gt0_rxpolarity_in : in STD_LOGIC;
    gt0_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt0_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpen : in STD_LOGIC;
    gt0_drpwe : in STD_LOGIC;
    gt0_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drprdy : out STD_LOGIC;
    gt0_eyescandataerror_out : out STD_LOGIC;
    gt0_eyescantrigger_in : in STD_LOGIC;
    gt0_eyescanreset_in : in STD_LOGIC;
    gt0_txprbsforceerr_in : in STD_LOGIC;
    gt0_txpcsreset_in : in STD_LOGIC;
    gt0_txpmareset_in : in STD_LOGIC;
    gt0_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt0_rxcdrhold_in : in STD_LOGIC;
    gt0_rxprbserr_out : out STD_LOGIC;
    gt0_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_rxprbscntreset_in : in STD_LOGIC;
    gt0_rxbufreset_in : in STD_LOGIC;
    gt0_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_rxbyteisaligned_out : out STD_LOGIC;
    gt0_rxbyterealign_out : out STD_LOGIC;
    gt0_rxcommadet_out : out STD_LOGIC;
    gt0_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt0_rxpcsreset_in : in STD_LOGIC;
    gt0_rxpmareset_in : in STD_LOGIC;
    gt0_rxlpmen_in : in STD_LOGIC;
    gt0_rxdfelpmreset_in : in STD_LOGIC;
    gt0_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt0_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_txresetdone_out : out STD_LOGIC;
    gt1_rxresetdone_out : out STD_LOGIC;
    gt1_cplllock_out : out STD_LOGIC;
    gt1_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt1_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt1_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_txpolarity_in : in STD_LOGIC;
    gt1_txinhibit_in : in STD_LOGIC;
    gt1_rxpolarity_in : in STD_LOGIC;
    gt1_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt1_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpen : in STD_LOGIC;
    gt1_drpwe : in STD_LOGIC;
    gt1_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drprdy : out STD_LOGIC;
    gt1_eyescandataerror_out : out STD_LOGIC;
    gt1_eyescantrigger_in : in STD_LOGIC;
    gt1_eyescanreset_in : in STD_LOGIC;
    gt1_txprbsforceerr_in : in STD_LOGIC;
    gt1_txpcsreset_in : in STD_LOGIC;
    gt1_txpmareset_in : in STD_LOGIC;
    gt1_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_rxcdrhold_in : in STD_LOGIC;
    gt1_rxprbserr_out : out STD_LOGIC;
    gt1_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_rxprbscntreset_in : in STD_LOGIC;
    gt1_rxbufreset_in : in STD_LOGIC;
    gt1_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt1_rxbyteisaligned_out : out STD_LOGIC;
    gt1_rxbyterealign_out : out STD_LOGIC;
    gt1_rxcommadet_out : out STD_LOGIC;
    gt1_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt1_rxpcsreset_in : in STD_LOGIC;
    gt1_rxpmareset_in : in STD_LOGIC;
    gt1_rxlpmen_in : in STD_LOGIC;
    gt1_rxdfelpmreset_in : in STD_LOGIC;
    gt1_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt1_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_txresetdone_out : out STD_LOGIC;
    gt2_rxresetdone_out : out STD_LOGIC;
    gt2_cplllock_out : out STD_LOGIC;
    gt2_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt2_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt2_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_txpolarity_in : in STD_LOGIC;
    gt2_txinhibit_in : in STD_LOGIC;
    gt2_rxpolarity_in : in STD_LOGIC;
    gt2_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt2_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpen : in STD_LOGIC;
    gt2_drpwe : in STD_LOGIC;
    gt2_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drprdy : out STD_LOGIC;
    gt2_eyescandataerror_out : out STD_LOGIC;
    gt2_eyescantrigger_in : in STD_LOGIC;
    gt2_eyescanreset_in : in STD_LOGIC;
    gt2_txprbsforceerr_in : in STD_LOGIC;
    gt2_txpcsreset_in : in STD_LOGIC;
    gt2_txpmareset_in : in STD_LOGIC;
    gt2_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_rxcdrhold_in : in STD_LOGIC;
    gt2_rxprbserr_out : out STD_LOGIC;
    gt2_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_rxprbscntreset_in : in STD_LOGIC;
    gt2_rxbufreset_in : in STD_LOGIC;
    gt2_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt2_rxbyteisaligned_out : out STD_LOGIC;
    gt2_rxbyterealign_out : out STD_LOGIC;
    gt2_rxcommadet_out : out STD_LOGIC;
    gt2_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt2_rxpcsreset_in : in STD_LOGIC;
    gt2_rxpmareset_in : in STD_LOGIC;
    gt2_rxlpmen_in : in STD_LOGIC;
    gt2_rxdfelpmreset_in : in STD_LOGIC;
    gt2_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt2_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_txresetdone_out : out STD_LOGIC;
    gt3_rxresetdone_out : out STD_LOGIC;
    gt3_cplllock_out : out STD_LOGIC;
    gt3_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt3_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt3_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_txpolarity_in : in STD_LOGIC;
    gt3_txinhibit_in : in STD_LOGIC;
    gt3_rxpolarity_in : in STD_LOGIC;
    gt3_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt3_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpen : in STD_LOGIC;
    gt3_drpwe : in STD_LOGIC;
    gt3_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drprdy : out STD_LOGIC;
    gt3_eyescandataerror_out : out STD_LOGIC;
    gt3_eyescantrigger_in : in STD_LOGIC;
    gt3_eyescanreset_in : in STD_LOGIC;
    gt3_txprbsforceerr_in : in STD_LOGIC;
    gt3_txpcsreset_in : in STD_LOGIC;
    gt3_txpmareset_in : in STD_LOGIC;
    gt3_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_rxcdrhold_in : in STD_LOGIC;
    gt3_rxprbserr_out : out STD_LOGIC;
    gt3_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_rxprbscntreset_in : in STD_LOGIC;
    gt3_rxbufreset_in : in STD_LOGIC;
    gt3_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt3_rxbyteisaligned_out : out STD_LOGIC;
    gt3_rxbyterealign_out : out STD_LOGIC;
    gt3_rxcommadet_out : out STD_LOGIC;
    gt3_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt3_rxpcsreset_in : in STD_LOGIC;
    gt3_rxpmareset_in : in STD_LOGIC;
    gt3_rxlpmen_in : in STD_LOGIC;
    gt3_rxdfelpmreset_in : in STD_LOGIC;
    gt3_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt3_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt4_txresetdone_out : out STD_LOGIC;
    gt4_rxresetdone_out : out STD_LOGIC;
    gt4_cplllock_out : out STD_LOGIC;
    gt4_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt4_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt4_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt4_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt4_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt4_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_txpolarity_in : in STD_LOGIC;
    gt4_txinhibit_in : in STD_LOGIC;
    gt4_rxpolarity_in : in STD_LOGIC;
    gt4_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt4_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt4_drpen : in STD_LOGIC;
    gt4_drpwe : in STD_LOGIC;
    gt4_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt4_drprdy : out STD_LOGIC;
    gt4_eyescandataerror_out : out STD_LOGIC;
    gt4_eyescantrigger_in : in STD_LOGIC;
    gt4_eyescanreset_in : in STD_LOGIC;
    gt4_txprbsforceerr_in : in STD_LOGIC;
    gt4_txpcsreset_in : in STD_LOGIC;
    gt4_txpmareset_in : in STD_LOGIC;
    gt4_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt4_rxcdrhold_in : in STD_LOGIC;
    gt4_rxprbserr_out : out STD_LOGIC;
    gt4_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt4_rxprbscntreset_in : in STD_LOGIC;
    gt4_rxbufreset_in : in STD_LOGIC;
    gt4_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt4_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt4_rxbyteisaligned_out : out STD_LOGIC;
    gt4_rxbyterealign_out : out STD_LOGIC;
    gt4_rxcommadet_out : out STD_LOGIC;
    gt4_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt4_rxpcsreset_in : in STD_LOGIC;
    gt4_rxpmareset_in : in STD_LOGIC;
    gt4_rxlpmen_in : in STD_LOGIC;
    gt4_rxdfelpmreset_in : in STD_LOGIC;
    gt4_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt4_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt5_txresetdone_out : out STD_LOGIC;
    gt5_rxresetdone_out : out STD_LOGIC;
    gt5_cplllock_out : out STD_LOGIC;
    gt5_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt5_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt5_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt5_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt5_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt5_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_txpolarity_in : in STD_LOGIC;
    gt5_txinhibit_in : in STD_LOGIC;
    gt5_rxpolarity_in : in STD_LOGIC;
    gt5_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt5_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt5_drpen : in STD_LOGIC;
    gt5_drpwe : in STD_LOGIC;
    gt5_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt5_drprdy : out STD_LOGIC;
    gt5_eyescandataerror_out : out STD_LOGIC;
    gt5_eyescantrigger_in : in STD_LOGIC;
    gt5_eyescanreset_in : in STD_LOGIC;
    gt5_txprbsforceerr_in : in STD_LOGIC;
    gt5_txpcsreset_in : in STD_LOGIC;
    gt5_txpmareset_in : in STD_LOGIC;
    gt5_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt5_rxcdrhold_in : in STD_LOGIC;
    gt5_rxprbserr_out : out STD_LOGIC;
    gt5_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt5_rxprbscntreset_in : in STD_LOGIC;
    gt5_rxbufreset_in : in STD_LOGIC;
    gt5_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt5_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt5_rxbyteisaligned_out : out STD_LOGIC;
    gt5_rxbyterealign_out : out STD_LOGIC;
    gt5_rxcommadet_out : out STD_LOGIC;
    gt5_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt5_rxpcsreset_in : in STD_LOGIC;
    gt5_rxpmareset_in : in STD_LOGIC;
    gt5_rxlpmen_in : in STD_LOGIC;
    gt5_rxdfelpmreset_in : in STD_LOGIC;
    gt5_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt5_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt6_txresetdone_out : out STD_LOGIC;
    gt6_rxresetdone_out : out STD_LOGIC;
    gt6_cplllock_out : out STD_LOGIC;
    gt6_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt6_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt6_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt6_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt6_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt6_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_txpolarity_in : in STD_LOGIC;
    gt6_txinhibit_in : in STD_LOGIC;
    gt6_rxpolarity_in : in STD_LOGIC;
    gt6_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt6_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt6_drpen : in STD_LOGIC;
    gt6_drpwe : in STD_LOGIC;
    gt6_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt6_drprdy : out STD_LOGIC;
    gt6_eyescandataerror_out : out STD_LOGIC;
    gt6_eyescantrigger_in : in STD_LOGIC;
    gt6_eyescanreset_in : in STD_LOGIC;
    gt6_txprbsforceerr_in : in STD_LOGIC;
    gt6_txpcsreset_in : in STD_LOGIC;
    gt6_txpmareset_in : in STD_LOGIC;
    gt6_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt6_rxcdrhold_in : in STD_LOGIC;
    gt6_rxprbserr_out : out STD_LOGIC;
    gt6_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt6_rxprbscntreset_in : in STD_LOGIC;
    gt6_rxbufreset_in : in STD_LOGIC;
    gt6_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt6_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt6_rxbyteisaligned_out : out STD_LOGIC;
    gt6_rxbyterealign_out : out STD_LOGIC;
    gt6_rxcommadet_out : out STD_LOGIC;
    gt6_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt6_rxpcsreset_in : in STD_LOGIC;
    gt6_rxpmareset_in : in STD_LOGIC;
    gt6_rxlpmen_in : in STD_LOGIC;
    gt6_rxdfelpmreset_in : in STD_LOGIC;
    gt6_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt6_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt7_txresetdone_out : out STD_LOGIC;
    gt7_rxresetdone_out : out STD_LOGIC;
    gt7_cplllock_out : out STD_LOGIC;
    gt7_loopback_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt7_rxpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt7_txpd_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt7_txpostcursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt7_txprecursor_in : in STD_LOGIC_VECTOR ( 4 downto 0 );
    gt7_txdiffctrl_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_txpolarity_in : in STD_LOGIC;
    gt7_txinhibit_in : in STD_LOGIC;
    gt7_rxpolarity_in : in STD_LOGIC;
    gt7_drpaddr : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt7_drpdi : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt7_drpen : in STD_LOGIC;
    gt7_drpwe : in STD_LOGIC;
    gt7_drpdo : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt7_drprdy : out STD_LOGIC;
    gt7_eyescandataerror_out : out STD_LOGIC;
    gt7_eyescantrigger_in : in STD_LOGIC;
    gt7_eyescanreset_in : in STD_LOGIC;
    gt7_txprbsforceerr_in : in STD_LOGIC;
    gt7_txpcsreset_in : in STD_LOGIC;
    gt7_txpmareset_in : in STD_LOGIC;
    gt7_txbufstatus_out : out STD_LOGIC_VECTOR ( 1 downto 0 );
    gt7_rxcdrhold_in : in STD_LOGIC;
    gt7_rxprbserr_out : out STD_LOGIC;
    gt7_rxprbssel_in : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt7_rxprbscntreset_in : in STD_LOGIC;
    gt7_rxbufreset_in : in STD_LOGIC;
    gt7_rxbufstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt7_rxstatus_out : out STD_LOGIC_VECTOR ( 2 downto 0 );
    gt7_rxbyteisaligned_out : out STD_LOGIC;
    gt7_rxbyterealign_out : out STD_LOGIC;
    gt7_rxcommadet_out : out STD_LOGIC;
    gt7_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt7_rxpcsreset_in : in STD_LOGIC;
    gt7_rxpmareset_in : in STD_LOGIC;
    gt7_rxlpmen_in : in STD_LOGIC;
    gt7_rxdfelpmreset_in : in STD_LOGIC;
    gt7_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt7_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    tx_sys_reset : in STD_LOGIC;
    rx_sys_reset : in STD_LOGIC;
    tx_reset_gt : in STD_LOGIC;
    rx_reset_gt : in STD_LOGIC;
    tx_reset_done : out STD_LOGIC;
    rx_reset_done : out STD_LOGIC;
    qpll_refclk : in STD_LOGIC;
    common0_qpll_lock_out : out STD_LOGIC;
    common0_qpll_refclk_out : out STD_LOGIC;
    common0_qpll_clk_out : out STD_LOGIC;
    common1_qpll_lock_out : out STD_LOGIC;
    common1_qpll_refclk_out : out STD_LOGIC;
    common1_qpll_clk_out : out STD_LOGIC;
    rxencommaalign : in STD_LOGIC;
    tx_core_clk : in STD_LOGIC;
    txoutclk : out STD_LOGIC;
    rx_core_clk : in STD_LOGIC;
    rxoutclk : out STD_LOGIC;
    drpclk : in STD_LOGIC;
    gt_prbssel : in STD_LOGIC_VECTOR ( 2 downto 0 );
    gt0_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt1_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt2_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt3_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt4_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt5_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt6_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt7_txcharisk : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_txdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt0_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt1_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt2_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt3_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt4_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt5_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt6_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt7_rxcharisk : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_rxdisperr : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_rxnotintable : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_rxdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    rxn_in : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rxp_in : in STD_LOGIC_VECTOR ( 7 downto 0 );
    txn_out : out STD_LOGIC_VECTOR ( 7 downto 0 );
    txp_out : out STD_LOGIC_VECTOR ( 7 downto 0 )
  );

end jesd204_0_phy;

architecture stub of jesd204_0_phy is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "gt0_txresetdone_out,gt0_rxresetdone_out,gt0_cplllock_out,gt0_loopback_in[2:0],gt0_rxpd_in[1:0],gt0_txpd_in[1:0],gt0_txpostcursor_in[4:0],gt0_txprecursor_in[4:0],gt0_txdiffctrl_in[3:0],gt0_txpolarity_in,gt0_txinhibit_in,gt0_rxpolarity_in,gt0_drpaddr[8:0],gt0_drpdi[15:0],gt0_drpen,gt0_drpwe,gt0_drpdo[15:0],gt0_drprdy,gt0_eyescandataerror_out,gt0_eyescantrigger_in,gt0_eyescanreset_in,gt0_txprbsforceerr_in,gt0_txpcsreset_in,gt0_txpmareset_in,gt0_txbufstatus_out[1:0],gt0_rxcdrhold_in,gt0_rxprbserr_out,gt0_rxprbssel_in[2:0],gt0_rxprbscntreset_in,gt0_rxbufreset_in,gt0_rxbufstatus_out[2:0],gt0_rxstatus_out[2:0],gt0_rxbyteisaligned_out,gt0_rxbyterealign_out,gt0_rxcommadet_out,gt0_dmonitorout_out[14:0],gt0_rxpcsreset_in,gt0_rxpmareset_in,gt0_rxlpmen_in,gt0_rxdfelpmreset_in,gt0_rxmonitorout_out[6:0],gt0_rxmonitorsel_in[1:0],gt1_txresetdone_out,gt1_rxresetdone_out,gt1_cplllock_out,gt1_loopback_in[2:0],gt1_rxpd_in[1:0],gt1_txpd_in[1:0],gt1_txpostcursor_in[4:0],gt1_txprecursor_in[4:0],gt1_txdiffctrl_in[3:0],gt1_txpolarity_in,gt1_txinhibit_in,gt1_rxpolarity_in,gt1_drpaddr[8:0],gt1_drpdi[15:0],gt1_drpen,gt1_drpwe,gt1_drpdo[15:0],gt1_drprdy,gt1_eyescandataerror_out,gt1_eyescantrigger_in,gt1_eyescanreset_in,gt1_txprbsforceerr_in,gt1_txpcsreset_in,gt1_txpmareset_in,gt1_txbufstatus_out[1:0],gt1_rxcdrhold_in,gt1_rxprbserr_out,gt1_rxprbssel_in[2:0],gt1_rxprbscntreset_in,gt1_rxbufreset_in,gt1_rxbufstatus_out[2:0],gt1_rxstatus_out[2:0],gt1_rxbyteisaligned_out,gt1_rxbyterealign_out,gt1_rxcommadet_out,gt1_dmonitorout_out[14:0],gt1_rxpcsreset_in,gt1_rxpmareset_in,gt1_rxlpmen_in,gt1_rxdfelpmreset_in,gt1_rxmonitorout_out[6:0],gt1_rxmonitorsel_in[1:0],gt2_txresetdone_out,gt2_rxresetdone_out,gt2_cplllock_out,gt2_loopback_in[2:0],gt2_rxpd_in[1:0],gt2_txpd_in[1:0],gt2_txpostcursor_in[4:0],gt2_txprecursor_in[4:0],gt2_txdiffctrl_in[3:0],gt2_txpolarity_in,gt2_txinhibit_in,gt2_rxpolarity_in,gt2_drpaddr[8:0],gt2_drpdi[15:0],gt2_drpen,gt2_drpwe,gt2_drpdo[15:0],gt2_drprdy,gt2_eyescandataerror_out,gt2_eyescantrigger_in,gt2_eyescanreset_in,gt2_txprbsforceerr_in,gt2_txpcsreset_in,gt2_txpmareset_in,gt2_txbufstatus_out[1:0],gt2_rxcdrhold_in,gt2_rxprbserr_out,gt2_rxprbssel_in[2:0],gt2_rxprbscntreset_in,gt2_rxbufreset_in,gt2_rxbufstatus_out[2:0],gt2_rxstatus_out[2:0],gt2_rxbyteisaligned_out,gt2_rxbyterealign_out,gt2_rxcommadet_out,gt2_dmonitorout_out[14:0],gt2_rxpcsreset_in,gt2_rxpmareset_in,gt2_rxlpmen_in,gt2_rxdfelpmreset_in,gt2_rxmonitorout_out[6:0],gt2_rxmonitorsel_in[1:0],gt3_txresetdone_out,gt3_rxresetdone_out,gt3_cplllock_out,gt3_loopback_in[2:0],gt3_rxpd_in[1:0],gt3_txpd_in[1:0],gt3_txpostcursor_in[4:0],gt3_txprecursor_in[4:0],gt3_txdiffctrl_in[3:0],gt3_txpolarity_in,gt3_txinhibit_in,gt3_rxpolarity_in,gt3_drpaddr[8:0],gt3_drpdi[15:0],gt3_drpen,gt3_drpwe,gt3_drpdo[15:0],gt3_drprdy,gt3_eyescandataerror_out,gt3_eyescantrigger_in,gt3_eyescanreset_in,gt3_txprbsforceerr_in,gt3_txpcsreset_in,gt3_txpmareset_in,gt3_txbufstatus_out[1:0],gt3_rxcdrhold_in,gt3_rxprbserr_out,gt3_rxprbssel_in[2:0],gt3_rxprbscntreset_in,gt3_rxbufreset_in,gt3_rxbufstatus_out[2:0],gt3_rxstatus_out[2:0],gt3_rxbyteisaligned_out,gt3_rxbyterealign_out,gt3_rxcommadet_out,gt3_dmonitorout_out[14:0],gt3_rxpcsreset_in,gt3_rxpmareset_in,gt3_rxlpmen_in,gt3_rxdfelpmreset_in,gt3_rxmonitorout_out[6:0],gt3_rxmonitorsel_in[1:0],gt4_txresetdone_out,gt4_rxresetdone_out,gt4_cplllock_out,gt4_loopback_in[2:0],gt4_rxpd_in[1:0],gt4_txpd_in[1:0],gt4_txpostcursor_in[4:0],gt4_txprecursor_in[4:0],gt4_txdiffctrl_in[3:0],gt4_txpolarity_in,gt4_txinhibit_in,gt4_rxpolarity_in,gt4_drpaddr[8:0],gt4_drpdi[15:0],gt4_drpen,gt4_drpwe,gt4_drpdo[15:0],gt4_drprdy,gt4_eyescandataerror_out,gt4_eyescantrigger_in,gt4_eyescanreset_in,gt4_txprbsforceerr_in,gt4_txpcsreset_in,gt4_txpmareset_in,gt4_txbufstatus_out[1:0],gt4_rxcdrhold_in,gt4_rxprbserr_out,gt4_rxprbssel_in[2:0],gt4_rxprbscntreset_in,gt4_rxbufreset_in,gt4_rxbufstatus_out[2:0],gt4_rxstatus_out[2:0],gt4_rxbyteisaligned_out,gt4_rxbyterealign_out,gt4_rxcommadet_out,gt4_dmonitorout_out[14:0],gt4_rxpcsreset_in,gt4_rxpmareset_in,gt4_rxlpmen_in,gt4_rxdfelpmreset_in,gt4_rxmonitorout_out[6:0],gt4_rxmonitorsel_in[1:0],gt5_txresetdone_out,gt5_rxresetdone_out,gt5_cplllock_out,gt5_loopback_in[2:0],gt5_rxpd_in[1:0],gt5_txpd_in[1:0],gt5_txpostcursor_in[4:0],gt5_txprecursor_in[4:0],gt5_txdiffctrl_in[3:0],gt5_txpolarity_in,gt5_txinhibit_in,gt5_rxpolarity_in,gt5_drpaddr[8:0],gt5_drpdi[15:0],gt5_drpen,gt5_drpwe,gt5_drpdo[15:0],gt5_drprdy,gt5_eyescandataerror_out,gt5_eyescantrigger_in,gt5_eyescanreset_in,gt5_txprbsforceerr_in,gt5_txpcsreset_in,gt5_txpmareset_in,gt5_txbufstatus_out[1:0],gt5_rxcdrhold_in,gt5_rxprbserr_out,gt5_rxprbssel_in[2:0],gt5_rxprbscntreset_in,gt5_rxbufreset_in,gt5_rxbufstatus_out[2:0],gt5_rxstatus_out[2:0],gt5_rxbyteisaligned_out,gt5_rxbyterealign_out,gt5_rxcommadet_out,gt5_dmonitorout_out[14:0],gt5_rxpcsreset_in,gt5_rxpmareset_in,gt5_rxlpmen_in,gt5_rxdfelpmreset_in,gt5_rxmonitorout_out[6:0],gt5_rxmonitorsel_in[1:0],gt6_txresetdone_out,gt6_rxresetdone_out,gt6_cplllock_out,gt6_loopback_in[2:0],gt6_rxpd_in[1:0],gt6_txpd_in[1:0],gt6_txpostcursor_in[4:0],gt6_txprecursor_in[4:0],gt6_txdiffctrl_in[3:0],gt6_txpolarity_in,gt6_txinhibit_in,gt6_rxpolarity_in,gt6_drpaddr[8:0],gt6_drpdi[15:0],gt6_drpen,gt6_drpwe,gt6_drpdo[15:0],gt6_drprdy,gt6_eyescandataerror_out,gt6_eyescantrigger_in,gt6_eyescanreset_in,gt6_txprbsforceerr_in,gt6_txpcsreset_in,gt6_txpmareset_in,gt6_txbufstatus_out[1:0],gt6_rxcdrhold_in,gt6_rxprbserr_out,gt6_rxprbssel_in[2:0],gt6_rxprbscntreset_in,gt6_rxbufreset_in,gt6_rxbufstatus_out[2:0],gt6_rxstatus_out[2:0],gt6_rxbyteisaligned_out,gt6_rxbyterealign_out,gt6_rxcommadet_out,gt6_dmonitorout_out[14:0],gt6_rxpcsreset_in,gt6_rxpmareset_in,gt6_rxlpmen_in,gt6_rxdfelpmreset_in,gt6_rxmonitorout_out[6:0],gt6_rxmonitorsel_in[1:0],gt7_txresetdone_out,gt7_rxresetdone_out,gt7_cplllock_out,gt7_loopback_in[2:0],gt7_rxpd_in[1:0],gt7_txpd_in[1:0],gt7_txpostcursor_in[4:0],gt7_txprecursor_in[4:0],gt7_txdiffctrl_in[3:0],gt7_txpolarity_in,gt7_txinhibit_in,gt7_rxpolarity_in,gt7_drpaddr[8:0],gt7_drpdi[15:0],gt7_drpen,gt7_drpwe,gt7_drpdo[15:0],gt7_drprdy,gt7_eyescandataerror_out,gt7_eyescantrigger_in,gt7_eyescanreset_in,gt7_txprbsforceerr_in,gt7_txpcsreset_in,gt7_txpmareset_in,gt7_txbufstatus_out[1:0],gt7_rxcdrhold_in,gt7_rxprbserr_out,gt7_rxprbssel_in[2:0],gt7_rxprbscntreset_in,gt7_rxbufreset_in,gt7_rxbufstatus_out[2:0],gt7_rxstatus_out[2:0],gt7_rxbyteisaligned_out,gt7_rxbyterealign_out,gt7_rxcommadet_out,gt7_dmonitorout_out[14:0],gt7_rxpcsreset_in,gt7_rxpmareset_in,gt7_rxlpmen_in,gt7_rxdfelpmreset_in,gt7_rxmonitorout_out[6:0],gt7_rxmonitorsel_in[1:0],tx_sys_reset,rx_sys_reset,tx_reset_gt,rx_reset_gt,tx_reset_done,rx_reset_done,qpll_refclk,common0_qpll_lock_out,common0_qpll_refclk_out,common0_qpll_clk_out,common1_qpll_lock_out,common1_qpll_refclk_out,common1_qpll_clk_out,rxencommaalign,tx_core_clk,txoutclk,rx_core_clk,rxoutclk,drpclk,gt_prbssel[2:0],gt0_txcharisk[3:0],gt0_txdata[31:0],gt1_txcharisk[3:0],gt1_txdata[31:0],gt2_txcharisk[3:0],gt2_txdata[31:0],gt3_txcharisk[3:0],gt3_txdata[31:0],gt4_txcharisk[3:0],gt4_txdata[31:0],gt5_txcharisk[3:0],gt5_txdata[31:0],gt6_txcharisk[3:0],gt6_txdata[31:0],gt7_txcharisk[3:0],gt7_txdata[31:0],gt0_rxcharisk[3:0],gt0_rxdisperr[3:0],gt0_rxnotintable[3:0],gt0_rxdata[31:0],gt1_rxcharisk[3:0],gt1_rxdisperr[3:0],gt1_rxnotintable[3:0],gt1_rxdata[31:0],gt2_rxcharisk[3:0],gt2_rxdisperr[3:0],gt2_rxnotintable[3:0],gt2_rxdata[31:0],gt3_rxcharisk[3:0],gt3_rxdisperr[3:0],gt3_rxnotintable[3:0],gt3_rxdata[31:0],gt4_rxcharisk[3:0],gt4_rxdisperr[3:0],gt4_rxnotintable[3:0],gt4_rxdata[31:0],gt5_rxcharisk[3:0],gt5_rxdisperr[3:0],gt5_rxnotintable[3:0],gt5_rxdata[31:0],gt6_rxcharisk[3:0],gt6_rxdisperr[3:0],gt6_rxnotintable[3:0],gt6_rxdata[31:0],gt7_rxcharisk[3:0],gt7_rxdisperr[3:0],gt7_rxnotintable[3:0],gt7_rxdata[31:0],rxn_in[7:0],rxp_in[7:0],txn_out[7:0],txp_out[7:0]";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "jesd204_phy_v4_0_4,Vivado 2018.3";
begin
end;
