# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/jesd204_0.xci
# IP: The module: 'jesd204_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/jesd204_0.xci
# IP: The module: 'jesd204_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/DSIP/DSIP_EB_banji_kaifa/chengdu_BIT/project_vivado18.3_YTH2_ADDA_pgb4_3.2/project_1/project_1.srcs/sources_1/ip/jesd204_0/synth/jesd204_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jesd204_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
