# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/work_panyanjiao/02_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_pgb4_3/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_xbar_0/ADC_xbar_0.xci
# IP: The module: 'ADC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/work_panyanjiao/02_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_pgb4_3/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_xbar_0/ADC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/work_panyanjiao/02_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_pgb4_3/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_xbar_0/ADC_xbar_0.xci
# IP: The module: 'ADC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/work_panyanjiao/02_yth_pingguban/8T8R/project_vivado18.3_YTH2_ADDA_pgb4_3/project_1/project_1.srcs/sources_1/bd/ADC/ip/ADC_xbar_0/ADC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
